<template>
    <v-navbar
        pginicial="true"
        pgonline=0
        imagem="images/logo.png"
        handsonlink="{{route('handson')}}"
        mastopexialink="{{route('mastopexia')}}"
        gestaolink="{{route('gestao-e-marketing')}}"
        mamoplastialink="{{route('mamoplastia-de-aumento')}}"
    ></v-navbar>
</template>